language: ruby

before_script:
  - "rm -vf config/database.yml"
  - "cp -v config/travis/database.yml.travis.${DB} config/database.yml"
  - "bundle exec rake db:create db:migrate"

before_install:
  - gem install bundler

bundler_args: --without development production

rvm:
  - 2.2
  - 2.1
  - 2.0.0

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

gemfile:
  - Gemfile

